export const supportedCurrencyList = [
  {
    id: 1,
    currencyCode: 'AED',
    currencyName: 'UAE Dirham',
    currencyCountry: 'United Arab Emirates',
  },
  {
    id: 2,
    currencyCode: 'AFN',
    currencyName: 'Afghan Afghani',
    currencyCountry: 'Afghanistan',
  },
  {
    id: 3,
    currencyCode: 'ALL',
    currencyName: 'Albanian Lek',
    currencyCountry: 'Albania',
  },
  {
    id: 4,
    currencyCode: 'AMD',
    currencyName: 'Armenian Dram',
    currencyCountry: 'Armenia',
  },
  {
    id: 5,
    currencyCode: 'ANG',
    currencyName: 'Netherlands Antillian Guilder',
    currencyCountry: 'Netherlands Antilles',
  },
  {
    id: 6,
    currencyCode: 'AOA',
    currencyName: 'Angolan Kwanza',
    currencyCountry: 'Angola',
  },
  {
    id: 7,
    currencyCode: 'ARS',
    currencyName: 'Argentine Peso',
    currencyCountry: 'Argentina',
  },
  {
    id: 8,
    currencyCode: 'AUD',
    currencyName: 'Australian Dollar',
    currencyCountry: 'Australia',
  },
  {
    id: 9,
    currencyCode: 'AWG',
    currencyName: 'Aruban Florin',
    currencyCountry: 'Aruba',
  },
  {
    id: 10,
    currencyCode: 'AZN',
    currencyName: 'Azerbaijani Manat',
    currencyCountry: 'Azerbaijan',
  },
  {
    id: 11,
    currencyCode: 'BAM',
    currencyName: 'Bosnia and Herzegovina Mark',
    currencyCountry: 'Bosnia and Herzegovina',
  },
  {
    id: 12,
    currencyCode: 'BBD',
    currencyName: 'Barbados Dollar',
    currencyCountry: 'Barbados',
  },
  {
    id: 13,
    currencyCode: 'BDT',
    currencyName: 'Bangladeshi Taka',
    currencyCountry: 'Bangladesh',
  },
  {
    id: 14,
    currencyCode: 'BGN',
    currencyName: 'Bulgarian Lev',
    currencyCountry: 'Bulgaria',
  },
  {
    id: 15,
    currencyCode: 'BHD',
    currencyName: 'Bahraini Dinar',
    currencyCountry: 'Bahrain',
  },
  {
    id: 16,
    currencyCode: 'BIF',
    currencyName: 'Burundian Franc',
    currencyCountry: 'Burundi',
  },
  {
    id: 17,
    currencyCode: 'BMD',
    currencyName: 'Bermudian Dollar',
    currencyCountry: 'Bermuda',
  },
  {
    id: 18,
    currencyCode: 'BND',
    currencyName: 'Brunei Dollar',
    currencyCountry: 'Brunei',
  },
  {
    id: 19,
    currencyCode: 'BOB',
    currencyName: 'Bolivian Boliviano',
    currencyCountry: 'Bolivia',
  },
  {
    id: 20,
    currencyCode: 'BRL',
    currencyName: 'Brazilian Real',
    currencyCountry: 'Brazil',
  },
  {
    id: 21,
    currencyCode: 'BSD',
    currencyName: 'Bahamian Dollar',
    currencyCountry: 'Bahamas',
  },
  {
    id: 22,
    currencyCode: 'BTN',
    currencyName: 'Bhutanese Ngultrum',
    currencyCountry: 'Bhutan',
  },
  {
    id: 23,
    currencyCode: 'BWP',
    currencyName: 'Botswana Pula',
    currencyCountry: 'Botswana',
  },
  {
    id: 24,
    currencyCode: 'BYN',
    currencyName: 'Belarusian Ruble',
    currencyCountry: 'Belarus',
  },
  {
    id: 25,
    currencyCode: 'BZD',
    currencyName: 'Belize Dollar',
    currencyCountry: 'Belize',
  },
  {
    id: 26,
    currencyCode: 'CAD',
    currencyName: 'Canadian Dollar',
    currencyCountry: 'Canada',
  },
  {
    id: 27,
    currencyCode: 'CDF',
    currencyName: 'Congolese Franc',
    currencyCountry: 'Democratic Republic of the Congo',
  },
  {
    id: 28,
    currencyCode: 'CHF',
    currencyName: 'Swiss Franc',
    currencyCountry: 'Switzerland',
  },
  {
    id: 29,
    currencyCode: 'CLP',
    currencyName: 'Chilean Peso',
    currencyCountry: 'Chile',
  },
  {
    id: 30,
    currencyCode: 'CNY',
    currencyName: 'Chinese Renminbi',
    currencyCountry: 'China',
  },
  {
    id: 31,
    currencyCode: 'COP',
    currencyName: 'Colombian Peso',
    currencyCountry: 'Colombia',
  },
  {
    id: 32,
    currencyCode: 'CRC',
    currencyName: 'Costa Rican Colon',
    currencyCountry: 'Costa Rica',
  },
  {
    id: 33,
    currencyCode: 'CUP',
    currencyName: 'Cuban Peso',
    currencyCountry: 'Cuba',
  },
  {
    id: 34,
    currencyCode: 'CVE',
    currencyName: 'Cape Verdean Escudo',
    currencyCountry: 'Cape Verde',
  },
  {
    id: 35,
    currencyCode: 'CZK',
    currencyName: 'Czech Koruna',
    currencyCountry: 'Czech Republic',
  },
  {
    id: 36,
    currencyCode: 'DJF',
    currencyName: 'Djiboutian Franc',
    currencyCountry: 'Djibouti',
  },
  {
    id: 37,
    currencyCode: 'DKK',
    currencyName: 'Danish Krone',
    currencyCountry: 'Denmark',
  },
  {
    id: 38,
    currencyCode: 'DOP',
    currencyName: 'Dominican Peso',
    currencyCountry: 'Dominican Republic',
  },
  {
    id: 39,
    currencyCode: 'DZD',
    currencyName: 'Algerian Dinar',
    currencyCountry: 'Algeria',
  },
  {
    id: 40,
    currencyCode: 'EGP',
    currencyName: 'Egyptian Pound',
    currencyCountry: 'Egypt',
  },
  {
    id: 41,
    currencyCode: 'ERN',
    currencyName: 'Eritrean Nakfa',
    currencyCountry: 'Eritrea',
  },
  {
    id: 42,
    currencyCode: 'ETB',
    currencyName: 'Ethiopian Birr',
    currencyCountry: 'Ethiopia',
  },
  {
    id: 43,
    currencyCode: 'EUR',
    currencyName: 'Euro',
    currencyCountry: 'European Union',
  },
  {
    id: 44,
    currencyCode: 'FJD',
    currencyName: 'Fiji Dollar',
    currencyCountry: 'Fiji',
  },
  {
    id: 45,
    currencyCode: 'FKP',
    currencyName: 'Falkland Islands Pound',
    currencyCountry: 'Falkland Islands',
  },
  {
    id: 46,
    currencyCode: 'FOK',
    currencyName: 'Faroese Króna',
    currencyCountry: 'Faroe Islands',
  },
  {
    id: 47,
    currencyCode: 'GBP',
    currencyName: 'Pound Sterling',
    currencyCountry: 'United Kingdom',
  },
  {
    id: 48,
    currencyCode: 'GEL',
    currencyName: 'Georgian Lari',
    currencyCountry: 'Georgia',
  },
  {
    id: 49,
    currencyCode: 'GGP',
    currencyName: 'Guernsey Pound',
    currencyCountry: 'Guernsey',
  },
  {
    id: 50,
    currencyCode: 'GHS',
    currencyName: 'Ghanaian Cedi',
    currencyCountry: 'Ghana',
  },
  {
    id: 51,
    currencyCode: 'GIP',
    currencyName: 'Gibraltar Pound',
    currencyCountry: 'Gibraltar',
  },
  {
    id: 52,
    currencyCode: 'GMD',
    currencyName: 'Gambian Dalasi',
    currencyCountry: 'The Gambia',
  },
  {
    id: 53,
    currencyCode: 'GNF',
    currencyName: 'Guinean Franc',
    currencyCountry: 'Guinea',
  },
  {
    id: 54,
    currencyCode: 'GTQ',
    currencyName: 'Guatemalan Quetzal',
    currencyCountry: 'Guatemala',
  },
  {
    id: 55,
    currencyCode: 'GYD',
    currencyName: 'Guyanese Dollar',
    currencyCountry: 'Guyana',
  },
  {
    id: 56,
    currencyCode: 'HKD',
    currencyName: 'Hong Kong Dollar',
    currencyCountry: 'Hong Kong',
  },
  {
    id: 57,
    currencyCode: 'HNL',
    currencyName: 'Honduran Lempira',
    currencyCountry: 'Honduras',
  },
  {
    id: 58,
    currencyCode: 'HRK',
    currencyName: 'Croatian Kuna',
    currencyCountry: 'Croatia',
  },
  {
    id: 59,
    currencyCode: 'HTG',
    currencyName: 'Haitian Gourde',
    currencyCountry: 'Haiti',
  },
  {
    id: 60,
    currencyCode: 'HUF',
    currencyName: 'Hungarian Forint',
    currencyCountry: 'Hungary',
  },
  {
    id: 61,
    currencyCode: 'IDR',
    currencyName: 'Indonesian Rupiah',
    currencyCountry: 'Indonesia',
  },
  {
    id: 62,
    currencyCode: 'ILS',
    currencyName: 'Israeli New Shekel',
    currencyCountry: 'Israel',
  },
  {
    id: 63,
    currencyCode: 'IMP',
    currencyName: 'Manx Pound',
    currencyCountry: 'Isle of Man',
  },
  {
    id: 64,
    currencyCode: 'INR',
    currencyName: 'Indian Rupee',
    currencyCountry: 'India',
  },
  {
    id: 65,
    currencyCode: 'IQD',
    currencyName: 'Iraqi Dinar',
    currencyCountry: 'Iraq',
  },
  {
    id: 66,
    currencyCode: 'IRR',
    currencyName: 'Iranian Rial',
    currencyCountry: 'Iran',
  },
  {
    id: 67,
    currencyCode: 'ISK',
    currencyName: 'Icelandic Króna',
    currencyCountry: 'Iceland',
  },
  {
    id: 68,
    currencyCode: 'JEP',
    currencyName: 'Jersey Pound',
    currencyCountry: 'Jersey',
  },
  {
    id: 69,
    currencyCode: 'JMD',
    currencyName: 'Jamaican Dollar',
    currencyCountry: 'Jamaica',
  },
  {
    id: 70,
    currencyCode: 'JOD',
    currencyName: 'Jordanian Dinar',
    currencyCountry: 'Jordan',
  },
  {
    id: 71,
    currencyCode: 'JPY',
    currencyName: 'Japanese Yen',
    currencyCountry: 'Japan',
  },
  {
    id: 72,
    currencyCode: 'KES',
    currencyName: 'Kenyan Shilling',
    currencyCountry: 'Kenya',
  },
  {
    id: 73,
    currencyCode: 'KGS',
    currencyName: 'Kyrgyzstani Som',
    currencyCountry: 'Kyrgyzstan',
  },
  {
    id: 74,
    currencyCode: 'KHR',
    currencyName: 'Cambodian Riel',
    currencyCountry: 'Cambodia',
  },
  {
    id: 75,
    currencyCode: 'KID',
    currencyName: 'Kiribati Dollar',
    currencyCountry: 'Kiribati',
  },
  {
    id: 76,
    currencyCode: 'KMF',
    currencyName: 'Comorian Franc',
    currencyCountry: 'Comoros',
  },
  {
    id: 77,
    currencyCode: 'KRW',
    currencyName: 'South Korean Won',
    currencyCountry: 'South Korea',
  },
  {
    id: 78,
    currencyCode: 'KWD',
    currencyName: 'Kuwaiti Dinar',
    currencyCountry: 'Kuwait',
  },
  {
    id: 79,
    currencyCode: 'KYD',
    currencyName: 'Cayman Islands Dollar',
    currencyCountry: 'Cayman Islands',
  },
  {
    id: 80,
    currencyCode: 'KZT',
    currencyName: 'Kazakhstani Tenge',
    currencyCountry: 'Kazakhstan',
  },
  {
    id: 81,
    currencyCode: 'LAK',
    currencyName: 'Lao Kip',
    currencyCountry: 'Laos',
  },
  {
    id: 82,
    currencyCode: 'LBP',
    currencyName: 'Lebanese Pound',
    currencyCountry: 'Lebanon',
  },
  {
    id: 83,
    currencyCode: 'LKR',
    currencyName: 'Sri Lanka Rupee',
    currencyCountry: 'Sri Lanka',
  },
  {
    id: 84,
    currencyCode: 'LRD',
    currencyName: 'Liberian Dollar',
    currencyCountry: 'Liberia',
  },
  {
    id: 85,
    currencyCode: 'LSL',
    currencyName: 'Lesotho Loti',
    currencyCountry: 'Lesotho',
  },
  {
    id: 86,
    currencyCode: 'LYD',
    currencyName: 'Libyan Dinar',
    currencyCountry: 'Libya',
  },
  {
    id: 87,
    currencyCode: 'MAD',
    currencyName: 'Moroccan Dirham',
    currencyCountry: 'Morocco',
  },
  {
    id: 88,
    currencyCode: 'MDL',
    currencyName: 'Moldovan Leu',
    currencyCountry: 'Moldova',
  },
  {
    id: 89,
    currencyCode: 'MGA',
    currencyName: 'Malagasy Ariary',
    currencyCountry: 'Madagascar',
  },
  {
    id: 90,
    currencyCode: 'MKD',
    currencyName: 'Macedonian Denar',
    currencyCountry: 'North Macedonia',
  },
  {
    id: 91,
    currencyCode: 'MMK',
    currencyName: 'Burmese Kyat',
    currencyCountry: 'Myanmar',
  },
  {
    id: 92,
    currencyCode: 'MNT',
    currencyName: 'Mongolian Tögrög',
    currencyCountry: 'Mongolia',
  },
  {
    id: 93,
    currencyCode: 'MOP',
    currencyName: 'Macanese Pataca',
    currencyCountry: 'Macau',
  },
  {
    id: 94,
    currencyCode: 'MRU',
    currencyName: 'Mauritanian Ouguiya',
    currencyCountry: 'Mauritania',
  },
  {
    id: 95,
    currencyCode: 'MUR',
    currencyName: 'Mauritian Rupee',
    currencyCountry: 'Mauritius',
  },
  {
    id: 96,
    currencyCode: 'MVR',
    currencyName: 'Maldivian Rufiyaa',
    currencyCountry: 'Maldives',
  },
  {
    id: 97,
    currencyCode: 'MWK',
    currencyName: 'Malawian Kwacha',
    currencyCountry: 'Malawi',
  },
  {
    id: 98,
    currencyCode: 'MXN',
    currencyName: 'Mexican Peso',
    currencyCountry: 'Mexico',
  },
  {
    id: 99,
    currencyCode: 'MYR',
    currencyName: 'Malaysian Ringgit',
    currencyCountry: 'Malaysia',
  },
  {
    id: 100,
    currencyCode: 'MZN',
    currencyName: 'Mozambican Metical',
    currencyCountry: 'Mozambique',
  },
  {
    id: 101,
    currencyCode: 'NAD',
    currencyName: 'Namibian Dollar',
    currencyCountry: 'Namibia',
  },
  {
    id: 102,
    currencyCode: 'NGN',
    currencyName: 'Nigerian Naira',
    currencyCountry: 'Nigeria',
  },
  {
    id: 103,
    currencyCode: 'NIO',
    currencyName: 'Nicaraguan Córdoba',
    currencyCountry: 'Nicaragua',
  },
  {
    id: 104,
    currencyCode: 'NOK',
    currencyName: 'Norwegian Krone',
    currencyCountry: 'Norway',
  },
  {
    id: 105,
    currencyCode: 'NPR',
    currencyName: 'Nepalese Rupee',
    currencyCountry: 'Nepal',
  },
  {
    id: 106,
    currencyCode: 'NZD',
    currencyName: 'New Zealand Dollar',
    currencyCountry: 'New Zealand',
  },
  {
    id: 107,
    currencyCode: 'OMR',
    currencyName: 'Omani Rial',
    currencyCountry: 'Oman',
  },
  {
    id: 108,
    currencyCode: 'PAB',
    currencyName: 'Panamanian Balboa',
    currencyCountry: 'Panama',
  },
  {
    id: 109,
    currencyCode: 'PEN',
    currencyName: 'Peruvian Sol',
    currencyCountry: 'Peru',
  },
  {
    id: 110,
    currencyCode: 'PGK',
    currencyName: 'Papua New Guinean Kina',
    currencyCountry: 'Papua New Guinea',
  },
  {
    id: 111,
    currencyCode: 'PHP',
    currencyName: 'Philippine Peso',
    currencyCountry: 'Philippines',
  },
  {
    id: 112,
    currencyCode: 'PKR',
    currencyName: 'Pakistani Rupee',
    currencyCountry: 'Pakistan',
  },
  {
    id: 113,
    currencyCode: 'PLN',
    currencyName: 'Polish Złoty',
    currencyCountry: 'Poland',
  },
  {
    id: 114,
    currencyCode: 'PYG',
    currencyName: 'Paraguayan Guaraní',
    currencyCountry: 'Paraguay',
  },
  {
    id: 115,
    currencyCode: 'QAR',
    currencyName: 'Qatari Riyal',
    currencyCountry: 'Qatar',
  },
  {
    id: 116,
    currencyCode: 'RON',
    currencyName: 'Romanian Leu',
    currencyCountry: 'Romania',
  },
  {
    id: 117,
    currencyCode: 'RSD',
    currencyName: 'Serbian Dinar',
    currencyCountry: 'Serbia',
  },
  {
    id: 118,
    currencyCode: 'RUB',
    currencyName: 'Russian Ruble',
    currencyCountry: 'Russia',
  },
  {
    id: 119,
    currencyCode: 'RWF',
    currencyName: 'Rwandan Franc',
    currencyCountry: 'Rwanda',
  },
  {
    id: 120,
    currencyCode: 'SAR',
    currencyName: 'Saudi Riyal',
    currencyCountry: 'Saudi Arabia',
  },
  {
    id: 121,
    currencyCode: 'SBD',
    currencyName: 'Solomon Islands Dollar',
    currencyCountry: 'Solomon Islands',
  },
  {
    id: 122,
    currencyCode: 'SCR',
    currencyName: 'Seychellois Rupee',
    currencyCountry: 'Seychelles',
  },
  {
    id: 123,
    currencyCode: 'SDG',
    currencyName: 'Sudanese Pound',
    currencyCountry: 'Sudan',
  },
  {
    id: 124,
    currencyCode: 'SEK',
    currencyName: 'Swedish Krona',
    currencyCountry: 'Sweden',
  },
  {
    id: 125,
    currencyCode: 'SGD',
    currencyName: 'Singapore Dollar',
    currencyCountry: 'Singapore',
  },
  {
    id: 126,
    currencyCode: 'SHP',
    currencyName: 'Saint Helena Pound',
    currencyCountry: 'Saint Helena',
  },
  {
    id: 127,
    currencyCode: 'SLE',
    currencyName: 'Sierra Leonean Leone',
    currencyCountry: 'Sierra Leone',
  },
  {
    id: 128,
    currencyCode: 'SOS',
    currencyName: 'Somali Shilling',
    currencyCountry: 'Somalia',
  },
  {
    id: 129,
    currencyCode: 'SRD',
    currencyName: 'Surinamese Dollar',
    currencyCountry: 'Suriname',
  },
  {
    id: 130,
    currencyCode: 'SSP',
    currencyName: 'South Sudanese Pound',
    currencyCountry: 'South Sudan',
  },
  {
    id: 131,
    currencyCode: 'STN',
    currencyName: 'São Tomé and Príncipe Dobra',
    currencyCountry: 'São Tomé and Príncipe',
  },
  {
    id: 132,
    currencyCode: 'SYP',
    currencyName: 'Syrian Pound',
    currencyCountry: 'Syria',
  },
  {
    id: 133,
    currencyCode: 'SZL',
    currencyName: 'Eswatini Lilangeni',
    currencyCountry: 'Eswatini',
  },
  {
    id: 134,
    currencyCode: 'THB',
    currencyName: 'Thai Baht',
    currencyCountry: 'Thailand',
  },
  {
    id: 135,
    currencyCode: 'TJS',
    currencyName: 'Tajikistani Somoni',
    currencyCountry: 'Tajikistan',
  },
  {
    id: 136,
    currencyCode: 'TMT',
    currencyName: 'Turkmenistan Manat',
    currencyCountry: 'Turkmenistan',
  },
  {
    id: 137,
    currencyCode: 'TND',
    currencyName: 'Tunisian Dinar',
    currencyCountry: 'Tunisia',
  },
  {
    id: 138,
    currencyCode: 'TOP',
    currencyName: 'Tongan Paʻanga',
    currencyCountry: 'Tonga',
  },
  {
    id: 139,
    currencyCode: 'TRY',
    currencyName: 'Turkish Lira',
    currencyCountry: 'Turkey',
  },
  {
    id: 140,
    currencyCode: 'TTD',
    currencyName: 'Trinidad and Tobago Dollar',
    currencyCountry: 'Trinidad and Tobago',
  },
  {
    id: 141,
    currencyCode: 'TVD',
    currencyName: 'Tuvaluan Dollar',
    currencyCountry: 'Tuvalu',
  },
  {
    id: 142,
    currencyCode: 'TWD',
    currencyName: 'New Taiwan Dollar',
    currencyCountry: 'Taiwan',
  },
  {
    id: 143,
    currencyCode: 'TZS',
    currencyName: 'Tanzanian Shilling',
    currencyCountry: 'Tanzania',
  },
  {
    id: 144,
    currencyCode: 'UAH',
    currencyName: 'Ukrainian Hryvnia',
    currencyCountry: 'Ukraine',
  },
  {
    id: 145,
    currencyCode: 'UGX',
    currencyName: 'Ugandan Shilling',
    currencyCountry: 'Uganda',
  },
  {
    id: 146,
    currencyCode: 'USD',
    currencyName: 'United States Dollar',
    currencyCountry: 'United States',
  },
  {
    id: 147,
    currencyCode: 'UYU',
    currencyName: 'Uruguayan Peso',
    currencyCountry: 'Uruguay',
  },
  {
    id: 148,
    currencyCode: 'UZS',
    currencyName: 'Uzbekistani Som',
    currencyCountry: 'Uzbekistan',
  },
  {
    id: 149,
    currencyCode: 'VES',
    currencyName: 'Venezuelan Bolívar Soberano',
    currencyCountry: 'Venezuela',
  },
  {
    id: 150,
    currencyCode: 'VND',
    currencyName: 'Vietnamese Đồng',
    currencyCountry: 'Vietnam',
  },
  {
    id: 151,
    currencyCode: 'VUV',
    currencyName: 'Vanuatu Vatu',
    currencyCountry: 'Vanuatu',
  },
  {
    id: 152,
    currencyCode: 'WST',
    currencyName: 'Samoan Tālā',
    currencyCountry: 'Samoa',
  },
  {
    id: 153,
    currencyCode: 'XAF',
    currencyName: 'Central African CFA Franc',
    currencyCountry: 'CEMAC',
  },
  {
    id: 154,
    currencyCode: 'XCD',
    currencyName: 'East Caribbean Dollar',
    currencyCountry: 'Organisation of Eastern Caribbean States',
  },
  {
    id: 155,
    currencyCode: 'XDR',
    currencyName: 'Special Drawing Rights',
    currencyCountry: 'International Monetary Fund',
  },
  {
    id: 156,
    currencyCode: 'XOF',
    currencyName: 'West African CFA franc',
    currencyCountry: 'CFA',
  },
  {
    id: 157,
    currencyCode: 'XPF',
    currencyName: 'CFP Franc',
    currencyCountry: "Collectivités d'Outre-Mer",
  },
  {
    id: 158,
    currencyCode: 'YER',
    currencyName: 'Yemeni Rial',
    currencyCountry: 'Yemen',
  },
  {
    id: 159,
    currencyCode: 'ZAR',
    currencyName: 'South African Rand',
    currencyCountry: 'South Africa',
  },
  {
    id: 160,
    currencyCode: 'ZMW',
    currencyName: 'Zambian Kwacha',
    currencyCountry: 'Zambia',
  },
  {
    id: 161,
    currencyCode: 'ZWL',
    currencyName: 'Zimbabwean Dollar',
    currencyCountry: 'Zimbabwe',
  },
];
